// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmrmF-3g__UrITIaERXDIgsZXgXUdgZ8Q',
    appId: '1:196324596020:web:019aa09ae3fee822ed6d61',
    messagingSenderId: '196324596020',
    projectId: 'biteful-45e01',
    authDomain: 'biteful-45e01.firebaseapp.com',
    storageBucket: 'biteful-45e01.firebasestorage.app',
    measurementId: 'G-8VGEB1GM2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3YqatyEtcaLyDQP4tCtY4K130uYnHMWU',
    appId: '1:196324596020:android:1571028dab4bebe1ed6d61',
    messagingSenderId: '196324596020',
    projectId: 'biteful-45e01',
    storageBucket: 'biteful-45e01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfeTb--eAzSYJ9xz53OgY9ZqFn7poWgDw',
    appId: '1:196324596020:ios:1ee119be302afe57ed6d61',
    messagingSenderId: '196324596020',
    projectId: 'biteful-45e01',
    storageBucket: 'biteful-45e01.firebasestorage.app',
    iosBundleId: 'com.example.biteful',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmrmF-3g__UrITIaERXDIgsZXgXUdgZ8Q',
    appId: '1:196324596020:web:3abb4feb7832dca1ed6d61',
    messagingSenderId: '196324596020',
    projectId: 'biteful-45e01',
    authDomain: 'biteful-45e01.firebaseapp.com',
    storageBucket: 'biteful-45e01.firebasestorage.app',
    measurementId: 'G-922FE0NDQS',
  );

}